### ISSUE TITLE
Form submitting in iOS issues

### ISSUE THREAD

**Issue by vitorudy** [TapFuse/eventSpark-website#1]
@Lauricio, I just noticed that js snippet does not work with iOS browser

 script.
    function submitForm() {
    var frm = document.getElementById('contact_form');
    frm.submit(); // Submit
    frm.reset(); // Reset
    return false; // Prevent page refresh
    };

If form submitted from a pc with any kind of browser, data is recorded in form responds spreadsheet, but for some reason when submitting from phone it gives blank field although there is a timestamp of the event in the form, but none of the form fields are transferred in the spreadsheet. Tried to look for a jquery similar solutions but so far had no results.

**Comment by PoBuchi** [comment]
@vitorudy as said on message, i will look into it now
